source $HOME/.config/nvim/conf/settings.vim
source $HOME/.config/nvim/conf/mappings.vim
source $HOME/.config/nvim/conf/plugins.vim
source $HOME/.config/nvim/conf/complete.vim
source $HOME/.config/nvim/conf/start-screen.vim
source $HOME/.config/nvim/conf/tex.vim
source $HOME/.config/nvim/conf/fzf.vim
source $HOME/.config/nvim/conf/buftabline.vim
source $HOME/.config/nvim/conf/neovide.vim
source $HOME/.config/nvim/conf/nerdtree.vim
source $HOME/.config/nvim/conf/ctags.vim
